In [13]:
import tensorflow as tf

#Define a constant
a=tf.constant('hello world')
print(a)
print(a.numpy())

tf.Tensor(b'hello world', shape=(), dtype=string)
b'hello world'


In [14]:
#Scalar constants
a=tf.constant(42)
b=tf.constant(3.14)
c=tf.constant("Hello,Tensorflow!")
print(a.numpy(),b.numpy(),c.numpy())

42 3.14 b'Hello,Tensorflow!'


In [15]:
#vector constants
a=tf.constant([1,2,3])
b=tf.constant([1.0,2.0,3.0])
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
[1 2 3]
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
[1. 2. 3.]


In [18]:
#martix constants
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[1.0,2.0,],[3.0,4.0]])
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
[[1. 2.]
 [3. 4.]]


In [22]:
#Higher
a=tf.constant([[[1,2,0],[3,4,0]],[[5,6,0],[7,8,0]]])
print(a)
print(a.numpy())


tf.Tensor(
[[[1 2 0]
  [3 4 0]]

 [[5 6 0]
  [7 8 0]]], shape=(2, 2, 3), dtype=int32)
[[[1 2 0]
  [3 4 0]]

 [[5 6 0]
  [7 8 0]]]


In [24]:
#Boolen constants
a=tf.constant(True)
print(a)
print(a.numpy())

tf.Tensor(True, shape=(), dtype=bool)
True


In [23]:
#special constants
a=tf.zeros(shape=(2,2))
b=tf.ones(shape=(3,3))
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
[[0. 0.]
 [0. 0.]]
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
import tensorflow as tf
tf.config.run_functions_eagerly(True)
a=tf.constant(5.0)
b=tf.constant(3.0)
c=tf.multiply(a,b)
result=a*b
print(result)
print(result.numpy())


tf.Tensor(15.0, shape=(), dtype=float32)
15.0


In [27]:
a=tf.constant([[1, 2],[3, 4]])
b=tf.constant([[1,2],[3,4]])
c=tf.matmul(a,b)
result = a @ b
print(result)
print(result.numpy())

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
[[ 7 10]
 [15 22]]


In [26]:
import tensorflow as tf
a = tf.constant(1.25)
print(a)
print(a.numpy())
b=tf.cast(a,dtype=tf.int32)
print(b)
print(b.numpy())

tf.Tensor(1.25, shape=(), dtype=float32)
1.25
tf.Tensor(1, shape=(), dtype=int32)
1


In [29]:
import tensorflow as tf
x=tf.constant([[1.,2.,3.],[4.,5.,6.]])
e=tf.transpose(x)
print(e.numpy())

r=tf.reduce_sum(x)
print(r.numpy())

[[1. 4.]
 [2. 5.]
 [3. 6.]]
21.0


In [31]:
f=tf.concat([x,x,x], axis=0)
print(f.numpy())

[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]]


In [32]:
f=tf.concat([x,x,x], axis=1)
print(f.numpy())

[[1. 2. 3. 1. 2. 3. 1. 2. 3.]
 [4. 5. 6. 4. 5. 6. 4. 5. 6.]]


In [40]:
import tensorflow as tf
x=tf.constant([20,30,40,50,60,70])

logits=tf.constant([20.0,30.0,40.0,50.0,60.0,70.0])
softmax_probs=tf.nn.softmax(logits, axis=-1)
print(softmax_probs)


tf.Tensor(
[1.9286623e-22 4.2481610e-18 9.3571980e-14 2.0610600e-09 4.5397868e-05
 9.9995458e-01], shape=(6,), dtype=float32)


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/DAP_TEAM1/22A81A0508/WhatsApp Chat with Maggi.txt',sep='\t')
print(df)

   4/11/23, 11:09 AM - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
0   5/9/23, 7:01 PM - Disappearing messages were t...                                                                                                             
1   5/9/23, 7:01 PM - Maggi: no need to change any...                                                                                                             
2   5/9/23, 7:01 PM - Maggi: ELLIPSE-GENERAL METHO...                                                                                                             
3                  ELLIPSE-GENERAL METHOD-Layout1.pdf                                                                                                             
4   5/9/23, 7:02 PM - ༒ᴾᴿᴼ°᭄ᏦᎪMAL༒: You deleted th...                                                                                                             
..                    

In [10]:
pip install fpdf

In [11]:
import pandas as pd
from fpdf import FPDF

data_str = df.to_string(index=False)

# Initialize the PDF
pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", size=12)

# Add the DataFrame content to the PDF
# Encode the string using UTF-8 to avoid UnicodeEncodeError
pdf.multi_cell(0, 10, data_str.encode('utf-8').decode('latin-1'))

# Save the PDF file
pdf.output("/content/WhatsApp_Chat.pdf")

print("PDF successfully created!")

PDF successfully created!
